### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by sgasser** [ejbeaty/ChattyKathy#5]
On android is not working.

I get following error:
``
DOMException: play() can only be initiated by a user gesture.
(anonymous) @ ChattyKathy.js:177
playAudio @ ChattyKathy.js:166
``

**Comment by ejbeaty** [comment]
This SO post is likely related: https://stackoverflow.com/questions/38791760/domexception-play-can-only-be-initiated-by-a-user-gesture
