### ISSUE TITLE
save/doawnload audio file?!

### ISSUE THREAD

**Issue by Bahar1978** [ejbeaty/ChattyKathy#6]
Dear,
I can save the mp3 audio files, for each message fragment of a long text. 
I want to know if Amazon poly can provide any kind of identifier for each mp3 that it creates? And how it can be related to specific text/message?
Or we have to implement it ourselves?

Thanks in advance,

**Comment by ejbeaty** [comment]
you will need to implement this yourself as far as I know. All they do is send back a stream
